### ISSUE TITLE
[Epic] Cloud hosting (vs self hosting)

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/squeak#52]
It would be awesome to support a cloud version of Squeak to dogfood the app / for people who do not want to self-host.

Tasks/questions/ideas needed to make this happen, working list (feel free to overwrite add):

- [x] #63
- [x] #64
- [x] #65
- [x] Write a Postgres function similar to `get_is_admin()` to get the users organisation
- [x] Add Postgres policies to enable RLS for the tables (to prevent access to another orgs data)
- [x] Update the api routes to require an organisationId (and work out how to make this secure)
- [x] Update the snippet to add the concept of an organisation (adding a question, reply, signing up)
- [x] Add a method to disable the setup flow (for cloud)
- [x] Build a cloud setup flow
- [x] Allow for multiple config rows
